services:
  app:
    build: .
    container_name: gousers_api
    ports:
      - "8084:8084"
    env_file:
      - .env
    networks:
      - bianquiviri_network

networks:
  bianquiviri_network:
    external: true
